version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - CLICKHOUSE_HOST=clickhouse
    depends_on:
      - redis
      - clickhouse
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=1234
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
